export interface StationSeed {
  code: string;
  name: string;
  city: string;
  state: string;
}

export const STATIONS: StationSeed[] = [
  { code: "BOS", name: "Boston South Station", city: "Boston", state: "MA" },
  { code: "BBY", name: "Boston Back Bay", city: "Boston", state: "MA" },
  { code: "BON", name: "Boston North Station", city: "Boston", state: "MA" },
  { code: "RTE", name: "Westwood Route 128", city: "Westwood", state: "MA" },
  { code: "PVD", name: "Providence", city: "Providence", state: "RI" },
  { code: "KIN", name: "Kingston", city: "Kingston", state: "RI" },
  { code: "WLY", name: "Westerly", city: "Westerly", state: "RI" },
  { code: "MYS", name: "Mystic", city: "Mystic", state: "CT" },
  { code: "NLC", name: "New London", city: "New London", state: "CT" },
  { code: "OSB", name: "Old Saybrook", city: "Old Saybrook", state: "CT" },
  { code: "NHV", name: "New Haven Union Station", city: "New Haven", state: "CT" },
  { code: "BRP", name: "Bridgeport", city: "Bridgeport", state: "CT" },
  { code: "STM", name: "Stamford", city: "Stamford", state: "CT" },
  { code: "NRO", name: "New Rochelle", city: "New Rochelle", state: "NY" },
  { code: "NYP", name: "New York Penn Station", city: "New York", state: "NY" },
  { code: "NWK", name: "Newark Penn Station", city: "Newark", state: "NJ" },
  { code: "EWR", name: "Newark Airport", city: "Newark", state: "NJ" },
  { code: "MET", name: "Metropark", city: "Iselin", state: "NJ" },
  { code: "TRE", name: "Trenton", city: "Trenton", state: "NJ" },
  { code: "PHL", name: "Philadelphia 30th Street", city: "Philadelphia", state: "PA" },
  { code: "WIL", name: "Wilmington", city: "Wilmington", state: "DE" },
  { code: "ABE", name: "Aberdeen", city: "Aberdeen", state: "MD" },
  { code: "BAL", name: "Baltimore Penn Station", city: "Baltimore", state: "MD" },
  { code: "BWI", name: "BWI Thurgood Marshall Airport", city: "Baltimore", state: "MD" },
  { code: "NCR", name: "New Carrollton", city: "New Carrollton", state: "MD" },
  { code: "WAS", name: "Washington Union Station", city: "Washington", state: "DC" },
  { code: "ALX", name: "Alexandria", city: "Alexandria", state: "VA" },
  { code: "QAN", name: "Quantico", city: "Quantico", state: "VA" },
  { code: "FBG", name: "Fredericksburg", city: "Fredericksburg", state: "VA" },
  { code: "RVR", name: "Richmond Staples Mill", city: "Richmond", state: "VA" },
  { code: "RVM", name: "Richmond Main Street", city: "Richmond", state: "VA" },
  { code: "PTB", name: "Petersburg", city: "Petersburg", state: "VA" },
  { code: "NPN", name: "Newport News", city: "Newport News", state: "VA" },
  { code: "NFK", name: "Norfolk", city: "Norfolk", state: "VA" },
  { code: "WBG", name: "Williamsburg", city: "Williamsburg", state: "VA" },
  { code: "LYH", name: "Lynchburg", city: "Lynchburg", state: "VA" },
  { code: "RNK", name: "Roanoke", city: "Roanoke", state: "VA" },
  { code: "CLT", name: "Charlotte", city: "Charlotte", state: "NC" },
  { code: "RGH", name: "Raleigh Union Station", city: "Raleigh", state: "NC" },
  { code: "DNC", name: "Durham", city: "Durham", state: "NC" },
  { code: "GRN", name: "Greensboro", city: "Greensboro", state: "NC" },
  { code: "GBO", name: "Gastonia", city: "Gastonia", state: "NC" },
  { code: "SPS", name: "Spartanburg", city: "Spartanburg", state: "SC" },
  { code: "GRV", name: "Greenville", city: "Greenville", state: "SC" },
  { code: "GHS", name: "Charleston", city: "Charleston", state: "SC" },
  { code: "ATL", name: "Atlanta Peachtree", city: "Atlanta", state: "GA" },
  { code: "SAV", name: "Savannah", city: "Savannah", state: "GA" },
  { code: "JAX", name: "Jacksonville", city: "Jacksonville", state: "FL" },
  { code: "ORL", name: "Orlando", city: "Orlando", state: "FL" },
  { code: "WPK", name: "Winter Park", city: "Winter Park", state: "FL" },
  { code: "LAK", name: "Lakeland", city: "Lakeland", state: "FL" },
  { code: "TPA", name: "Tampa", city: "Tampa", state: "FL" },
  { code: "LAX", name: "Los Angeles Union Station", city: "Los Angeles", state: "CA" },
  { code: "SNA", name: "Santa Ana", city: "Santa Ana", state: "CA" },
  { code: "OSD", name: "Oceanside", city: "Oceanside", state: "CA" },
  { code: "SAN", name: "San Diego Santa Fe Depot", city: "San Diego", state: "CA" },
  { code: "FUL", name: "Fullerton", city: "Fullerton", state: "CA" },
  { code: "RIV", name: "Riverside", city: "Riverside", state: "CA" },
  { code: "SNB", name: "San Bernardino", city: "San Bernardino", state: "CA" },
  { code: "SBC", name: "Santa Barbara", city: "Santa Barbara", state: "CA" },
  { code: "SLO", name: "San Luis Obispo", city: "San Luis Obispo", state: "CA" },
  { code: "SJC", name: "San Jose Diridon", city: "San Jose", state: "CA" },
  { code: "OAC", name: "Oakland Coliseum", city: "Oakland", state: "CA" },
  { code: "OKJ", name: "Oakland Jack London Square", city: "Oakland", state: "CA" },
  { code: "EMY", name: "Emeryville", city: "Emeryville", state: "CA" },
  { code: "SFA", name: "San Francisco Salesforce Transit", city: "San Francisco", state: "CA" },
  { code: "SAC", name: "Sacramento", city: "Sacramento", state: "CA" },
  { code: "RDD", name: "Redding", city: "Redding", state: "CA" },
  { code: "EUG", name: "Eugene", city: "Eugene", state: "OR" },
  { code: "SLM", name: "Salem", city: "Salem", state: "OR" },
  { code: "PDX", name: "Portland Union Station", city: "Portland", state: "OR" },
  { code: "VAN", name: "Vancouver", city: "Vancouver", state: "WA" },
  { code: "KEL", name: "Kelso", city: "Kelso", state: "WA" },
  { code: "CTL", name: "Centralia", city: "Centralia", state: "WA" },
  { code: "OLW", name: "Olympia-Lacey", city: "Lacey", state: "WA" },
  { code: "TAC", name: "Tacoma", city: "Tacoma", state: "WA" },
  { code: "SEA", name: "Seattle King Street", city: "Seattle", state: "WA" },
  { code: "EVR", name: "Everett", city: "Everett", state: "WA" },
  { code: "BEL", name: "Bellingham", city: "Bellingham", state: "WA" },
  { code: "VAC", name: "Vancouver Pacific Central", city: "Vancouver", state: "BC" },
  { code: "CHI", name: "Chicago Union Station", city: "Chicago", state: "IL" },
  { code: "GLN", name: "Glenview", city: "Glenview", state: "IL" },
  { code: "NPV", name: "Naperville", city: "Naperville", state: "IL" },
  { code: "JOL", name: "Joliet", city: "Joliet", state: "IL" },
  { code: "MKE", name: "Milwaukee Intermodal", city: "Milwaukee", state: "WI" },
  { code: "MKA", name: "Milwaukee Airport", city: "Milwaukee", state: "WI" },
  { code: "MSP", name: "St. Paul Union Depot", city: "St. Paul", state: "MN" },
  { code: "MSC", name: "Michigan City", city: "Michigan City", state: "IN" },
  { code: "NBU", name: "New Buffalo", city: "New Buffalo", state: "MI" },
  { code: "KAL", name: "Kalamazoo", city: "Kalamazoo", state: "MI" },
  { code: "BTL", name: "Battle Creek", city: "Battle Creek", state: "MI" },
  { code: "LNS", name: "East Lansing", city: "East Lansing", state: "MI" },
  { code: "DET", name: "Detroit", city: "Detroit", state: "MI" },
  { code: "PTH", name: "Port Huron", city: "Port Huron", state: "MI" },
  { code: "GRR", name: "Grand Rapids", city: "Grand Rapids", state: "MI" },
  { code: "IND", name: "Indianapolis", city: "Indianapolis", state: "IN" },
  { code: "CIN", name: "Cincinnati", city: "Cincinnati", state: "OH" },
  { code: "CLE", name: "Cleveland", city: "Cleveland", state: "OH" },
  { code: "TOL", name: "Toledo", city: "Toledo", state: "OH" },
  { code: "PIT", name: "Pittsburgh", city: "Pittsburgh", state: "PA" },
  { code: "HGD", name: "Huntingdon", city: "Huntingdon", state: "PA" },
  { code: "HAR", name: "Harrisburg", city: "Harrisburg", state: "PA" },
  { code: "LNC", name: "Lancaster", city: "Lancaster", state: "PA" },
  { code: "PAO", name: "Paoli", city: "Paoli", state: "PA" },
  { code: "EXT", name: "Exton", city: "Exton", state: "PA" },
  { code: "ARD", name: "Ardmore", city: "Ardmore", state: "PA" },
  { code: "ALB", name: "Albany-Rensselaer", city: "Rensselaer", state: "NY" },
  { code: "SDY", name: "Schenectady", city: "Schenectady", state: "NY" },
  { code: "UCA", name: "Utica", city: "Utica", state: "NY" },
  { code: "SYR", name: "Syracuse", city: "Syracuse", state: "NY" },
  { code: "ROC", name: "Rochester", city: "Rochester", state: "NY" },
  { code: "BUF", name: "Buffalo-Depew", city: "Depew", state: "NY" },
  { code: "BFX", name: "Buffalo Exchange Street", city: "Buffalo", state: "NY" },
  { code: "NFL", name: "Niagara Falls NY", city: "Niagara Falls", state: "NY" },
  { code: "TWO", name: "Toronto Union Station", city: "Toronto", state: "ON" },
  { code: "RHI", name: "Rhinecliff", city: "Rhinecliff", state: "NY" },
  { code: "POU", name: "Poughkeepsie", city: "Poughkeepsie", state: "NY" },
  { code: "CRT", name: "Croton-Harmon", city: "Croton-on-Hudson", state: "NY" },
  { code: "YNY", name: "Yonkers", city: "Yonkers", state: "NY" },
  { code: "SPG", name: "Springfield", city: "Springfield", state: "MA" },
  { code: "NHT", name: "Northampton", city: "Northampton", state: "MA" },
  { code: "GFD", name: "Greenfield", city: "Greenfield", state: "MA" },
  { code: "BRA", name: "Brattleboro", city: "Brattleboro", state: "VT" },
  { code: "BLF", name: "Bellows Falls", city: "Bellows Falls", state: "VT" },
  { code: "WRJ", name: "White River Junction", city: "White River Junction", state: "VT" },
  { code: "RUD", name: "Rutland", city: "Rutland", state: "VT" },
  { code: "ESX", name: "Essex Junction", city: "Essex Junction", state: "VT" },
  { code: "SFA", name: "St. Albans", city: "St. Albans", state: "VT" },
  { code: "MTR", name: "Montreal Central Station", city: "Montreal", state: "QC" },
  { code: "POR", name: "Portland", city: "Portland", state: "ME" },
  { code: "FRE", name: "Freeport", city: "Freeport", state: "ME" },
  { code: "BRK", name: "Brunswick", city: "Brunswick", state: "ME" },
  { code: "HHL", name: "Haverhill", city: "Haverhill", state: "MA" },
  { code: "WOB", name: "Woburn", city: "Woburn", state: "MA" },
  { code: "NFS", name: "Niagara Falls ON", city: "Niagara Falls", state: "ON" },
  { code: "STL", name: "St. Louis Gateway", city: "St. Louis", state: "MO" },
  { code: "KCY", name: "Kansas City", city: "Kansas City", state: "MO" },
  { code: "OMA", name: "Omaha", city: "Omaha", state: "NE" },
  { code: "LNK", name: "Lincoln", city: "Lincoln", state: "NE" },
  { code: "DEN", name: "Denver Union Station", city: "Denver", state: "CO" },
  { code: "GSC", name: "Glenwood Springs", city: "Glenwood Springs", state: "CO" },
  { code: "GJT", name: "Grand Junction", city: "Grand Junction", state: "CO" },
  { code: "SLC", name: "Salt Lake City", city: "Salt Lake City", state: "UT" },
  { code: "RNO", name: "Reno", city: "Reno", state: "NV" },
  { code: "FLG", name: "Flagstaff", city: "Flagstaff", state: "AZ" },
  { code: "ABQ", name: "Albuquerque", city: "Albuquerque", state: "NM" },
  { code: "LVS", name: "Las Vegas NM", city: "Las Vegas", state: "NM" },
  { code: "TUS", name: "Tucson", city: "Tucson", state: "AZ" },
  { code: "YUM", name: "Yuma", city: "Yuma", state: "AZ" },
  { code: "ELP", name: "El Paso", city: "El Paso", state: "TX" },
  { code: "SAS", name: "San Antonio", city: "San Antonio", state: "TX" },
  { code: "AUS", name: "Austin", city: "Austin", state: "TX" },
  { code: "FTW", name: "Fort Worth", city: "Fort Worth", state: "TX" },
  { code: "DAL", name: "Dallas Union Station", city: "Dallas", state: "TX" },
  { code: "HOU", name: "Houston", city: "Houston", state: "TX" },
  { code: "MCG", name: "McGregor", city: "McGregor", state: "TX" },
  { code: "NOL", name: "New Orleans Union Passenger Terminal", city: "New Orleans", state: "LA" },
  { code: "MEM", name: "Memphis Central Station", city: "Memphis", state: "TN" },
  { code: "NBN", name: "Newbern-Dyersburg", city: "Newbern", state: "TN" },
  { code: "CRH", name: "Charlottesville", city: "Charlottesville", state: "VA" },
  { code: "CVS", name: "Charlottesville", city: "Charlottesville", state: "VA" },
  { code: "STA", name: "Staunton", city: "Staunton", state: "VA" },
  { code: "CLF", name: "Clifton Forge", city: "Clifton Forge", state: "VA" },
  { code: "HUN", name: "Huntington", city: "Huntington", state: "WV" },
  { code: "CHW", name: "Charleston WV", city: "Charleston", state: "WV" },
  { code: "CIN", name: "Cincinnati Union Terminal", city: "Cincinnati", state: "OH" },
  { code: "LAF", name: "Lafayette", city: "Lafayette", state: "IN" },
  { code: "DUN", name: "Dyer", city: "Dyer", state: "IN" },
  { code: "BRL", name: "Burlington", city: "Burlington", state: "IA" },
  { code: "MTZ", name: "Mount Pleasant", city: "Mount Pleasant", state: "IA" },
  { code: "OSC", name: "Ottumwa", city: "Ottumwa", state: "IA" },
  { code: "CRF", name: "Creston", city: "Creston", state: "IA" },
  { code: "OSC", name: "Osceola", city: "Osceola", state: "IA" },
  { code: "GBB", name: "Galesburg", city: "Galesburg", state: "IL" },
  { code: "PTH", name: "Port Huron", city: "Port Huron", state: "MI" },
  { code: "MKA", name: "Milwaukee Airport Rail Station", city: "Milwaukee", state: "WI" },
  { code: "WNL", name: "Winona", city: "Winona", state: "MN" },
  { code: "RDW", name: "Red Wing", city: "Red Wing", state: "MN" },
  { code: "FAR", name: "Fargo", city: "Fargo", state: "ND" },
  { code: "MOT", name: "Minot", city: "Minot", state: "ND" },
  { code: "WTN", name: "Williston", city: "Williston", state: "ND" },
  { code: "HAV", name: "Havre", city: "Havre", state: "MT" },
  { code: "GPK", name: "East Glacier Park", city: "East Glacier Park", state: "MT" },
  { code: "WGL", name: "West Glacier", city: "West Glacier", state: "MT" },
  { code: "WIH", name: "Whitefish", city: "Whitefish", state: "MT" },
  { code: "SPK", name: "Spokane", city: "Spokane", state: "WA" },
  { code: "WEN", name: "Wenatchee", city: "Wenatchee", state: "WA" },
  { code: "LWA", name: "Leavenworth", city: "Leavenworth", state: "WA" },
  { code: "EVE", name: "Everett", city: "Everett", state: "WA" },
  { code: "MIA", name: "Miami", city: "Miami", state: "FL" },
  { code: "HOL", name: "Hollywood", city: "Hollywood", state: "FL" },
  { code: "FTL", name: "Fort Lauderdale", city: "Fort Lauderdale", state: "FL" },
  { code: "DLB", name: "Deerfield Beach", city: "Deerfield Beach", state: "FL" },
  { code: "WPB", name: "West Palm Beach", city: "West Palm Beach", state: "FL" },
];

const unique = new Map<string, StationSeed>();
for (const station of STATIONS) {
  unique.set(station.code, station);
}

export const STATION_BY_CODE = unique;

export function stationLabel(code: string): string {
  const station = STATION_BY_CODE.get(code.toUpperCase());
  if (!station) return code;
  return `${station.name}`;
}

export function stationSubtitle(code: string): string {
  const station = STATION_BY_CODE.get(code.toUpperCase());
  if (!station) return code;
  return `${station.city}, ${station.state}`;
}
